include( ${CMAKE_CURRENT_LIST_DIR}/options.cmake )

include( ${CMAKE_CURRENT_LIST_DIR}/build.cmake )
include( ${CMAKE_CURRENT_LIST_DIR}/ccache.cmake )
include( ${CMAKE_CURRENT_LIST_DIR}/coverage.cmake )
include( ${CMAKE_CURRENT_LIST_DIR}/gcc.cmake )
include( ${CMAKE_CURRENT_LIST_DIR}/gold.cmake )
include( ${CMAKE_CURRENT_LIST_DIR}/thread.cmake )
include( ${CMAKE_CURRENT_LIST_DIR}/sanitizers.cmake )
include( ${CMAKE_CURRENT_LIST_DIR}/standart.cmake )
include( ${CMAKE_CURRENT_LIST_DIR}/warnings.cmake )
include( ${CMAKE_CURRENT_LIST_DIR}/werror.cmake )
