if( CXX_STANDARD_14 )
    set( CXX_STANDARD 14 )
elseif( CXX_STANDARD_17 )
    set( CXX_STANDARD 17 )
elseif( CXX_STANDARD_20 )
    set( CXX_STANDARD 20 )
else( )
    message( STATUS "C++ standard for all targets is not specified" )
    return( )
endif( )

message( STATUS "C++${CXX_STANDARD} standard is enabled" )
set( CMAKE_CXX_STANDARD ${CXX_STANDARD} )
set( CMAKE_CXX_STANDARD_REQUIRED ON )
